### ISSUE TITLE
Opacity modifier issue

### ISSUE THREAD

**Issue by ookamiiixd** [jacob-ebey/remix-shadcn#3]
When i tried to use the opacity modifier with extended colors e.g. `bg-primary/50`, i noticed that it doesn't work. Maybe it's because Tailwind didn't know where to inject the value, so i added the special placeholder manually into `lightDarkVar` function like this:
```js
function lightDarkVar(baseName) {
  return `var(--theme-light, hsl(var(--${baseName}) / <alpha-value>)) var(--theme-dark, hsl(var(--${baseName}-dark) / <alpha-value>))`;
}
```

But now there's another issue, if i understand it correctly, looks like tailwindcss didn't do global replace [here](https://github.com/tailwindlabs/tailwindcss/blob/86e389001b0cb52aa9338146a8f14892a3c0f198/src/util/pluginUtils.js#L126), so only the first occurance got replaced, in this case only the light mode that have the proper opacity value.

I currently solved this by patching tailwindcss, but this doesn't feel right. Is there a better way to work with this?

**Comment by micotodev** [comment]
The `<alpha-value>` issue has been fixed upstream but will need the above code snippet added as a PR once they've published a release.

Issue: tailwindlabs/tailwindcss#13716

Edit: 
 In fact, I think this upstream fix will only work when a string is passed, rather than a function; so the below edit may still be necessary. Changing the `lightDarkVar` function to the below worked for me.

```js
function lightDarkVar(baseName) {
	return ({ opacityValue = 1 }) => {
		return `var(--theme-light, hsl(var(--${baseName}) / ${opacityValue})) var(--theme-dark, hsl(var(--${baseName}-dark) / ${opacityValue}))`;
	}
}
```

**Comment by anyuruf** [comment]
Change the lightDarkVar function in  the tailwind.config. file ```function lightDarkVar(baseName) {
	return `var(--theme-light, hsl(var(--${baseName}) / <alpha-value>)) var(--theme-dark, hsl(var(--${baseName}-dark) / <alpha-value>))`;
}```
Check; https://tailwindcss.com/docs/customizing-colors#using-css-variables

**Comment by ookamiiixd** [comment]
Yep, this definitely has been fixed upstream. Closing this
