### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by ryan0x44** [jacob-ebey/remix-shadcn#5]
I recently went through this and I'm wondering whether you plan to include the Form component adjusted to work using the Remix Form component as a base?

The shadcn Form component is great from a UI/UX perspective, but doesn't work the way you'd expect a form to work in Remix.

I've found https://www.remix-validated-form.io/ to be the best library so far for easily handling form validation with Zod on both client-side and server-side using a single schema.

**Comment by jacob-ebey** [comment]
The template with login provides the conform library for the login form. Check out one of those branches to see how you can add it to the basic one.
