### ISSUE TITLE
Tailwind dark: prefix not working with dark mode theme switching

### ISSUE THREAD

**Issue by jbstewart** [jacob-ebey/remix-shadcn#6]
I am using this template (which is great by the way!) and I love that it has a theme switcher to support dark mode. However, the `dark:` Tailwind CSS prefix does not seem to work. Looking in the Tailwind docs, I noticed they say if you are going to change the theme manually you need to use the `selector` value instead of the [`class`] value for  `darkMode` in `tailwind.config.cjs`. I changed it to look like:
```
module.exports = {
	darkMode: "selector",
	...
```
but it had no effect. I then noticed in the docs that the to use the selector mode, you have to specify `dark`  in <html> tag like this:
```
<!-- Dark mode enabled -->
<html class="dark">
```

So I changed the `ThemeSwitcherSafeHTML` component like so:
```
export function ThemeSwitcherSafeHTML({
	children,
	lang,
	...props
}: React.HTMLProps<HTMLHtmlElement> & { lang: string }) {
	const dataTheme =
		typeof document === "undefined"
			? undefined
			: document.documentElement.getAttribute("data-theme") || undefined;

	return (
		<html {...props} lang={lang} data-theme={dataTheme} className={(dataTheme === "dark") ? "dark" : ""} >
			{children}
		</html>
	);
}
```

This works in either dark mode or light mode (which one seems to be based on whatever the theme was previously), but not both.  

Any suggestions would be most welcome - and thanks again for this starter template!

**Comment by jacob-ebey** [comment]
You are not meant to use "dark:" anything here. Rely on the colors provided or add more that have a dark and light value. Then do things like `color-primary`.
