### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by purecopy** [jacob-ebey/remix-shadcn#7]
I've encountered an issue with the template where there's a flash of unstyled content (FOUC) during the initial page load. I had the same issue with a new remix+vite project using tailwind.

## Steps to Reproduce:

1. Clone the repository and install dependencies.
2. Deploy the app using the provided build command.
3. Access the application in a web browser for the first time or hard refresh the page.

![CleanShot 2024-03-11 at 17 59 46](https://github.com/jacob-ebey/remix-shadcn/assets/30756432/24236b3e-8f91-46f8-bc77-14885a6f041b)

## Console
![CleanShot 2024-03-11 at 18 00 51@2x](https://github.com/jacob-ebey/remix-shadcn/assets/30756432/60ae26b1-0aa7-45bf-b9e3-3c607bac15ed)
![CleanShot 2024-03-11 at 18 09 15@2x](https://github.com/jacob-ebey/remix-shadcn/assets/30756432/8f879c94-f391-4133-a473-2f0357ee9f4b)

**Comment by jacob-ebey** [comment]
This is a plugin issue. If you see it in incognito mode the re-open.

**Comment by purecopy** [comment]
@jacob-ebey you are right. Somehow Adguard seems to break the initial page load in this example. Now I wonder how it can work on other pages. Thank you for pointing that out!

Edit: it seems like this issue was fixed in the React 18.3 canary version.
